// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OticaVisao.Infrastructure.Persistence;

#nullable disable

namespace OticaVisao.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901235004_SeedCatalog")]
    partial class SeedCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OticaVisao.Domain.Catalog.Frame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("shape");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("target_audience");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_frames_code");

                    b.ToTable("frames", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Brand = "Linha Visão",
                            Code = "ARM-001",
                            Color = "Preto",
                            IsActive = true,
                            IsPublished = true,
                            Model = "Clássica",
                            Price = 219m,
                            Shape = "Square",
                            StockQuantity = 1,
                            TargetAudience = "Adult",
                            Type = "Prescription"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Brand = "Linha Visão",
                            Code = "ARM-002",
                            Color = "Tartaruga",
                            IsActive = true,
                            IsPublished = true,
                            Model = "Leve",
                            Price = 219m,
                            Shape = "Round",
                            StockQuantity = 1,
                            TargetAudience = "Adult",
                            Type = "Prescription"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Brand = "Linha Visão",
                            Code = "ARM-003",
                            Color = "Preto",
                            IsActive = true,
                            IsPublished = true,
                            Model = "Solar",
                            Price = 219m,
                            Shape = "Aviator",
                            StockQuantity = 1,
                            TargetAudience = "Adult",
                            Type = "Sunglasses"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Brand = "Linha Visão",
                            Code = "ARM-004",
                            Color = "Azul",
                            IsActive = true,
                            IsPublished = true,
                            Model = "Colorida",
                            Price = 219m,
                            Shape = "Round",
                            StockQuantity = 1,
                            TargetAudience = "Child",
                            Type = "Prescription"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Brand = "Linha Visão",
                            Code = "ARM-005",
                            Color = "Dourado",
                            IsActive = true,
                            IsPublished = true,
                            Model = "Minimal",
                            Price = 219m,
                            Shape = "Other",
                            StockQuantity = 1,
                            TargetAudience = "Adult",
                            Type = "Prescription"
                        });
                });

            modelBuilder.Entity("OticaVisao.Domain.Catalog.Frame", b =>
                {
                    b.OwnsOne("OticaVisao.Domain.Catalog.FrameMeasurements", "Measurements", b1 =>
                        {
                            b1.Property<Guid>("FrameId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BridgeWidthMillimeters")
                                .HasColumnType("integer")
                                .HasColumnName("bridge_width_mm");

                            b1.Property<int>("LensWidthMillimeters")
                                .HasColumnType("integer")
                                .HasColumnName("lens_width_mm");

                            b1.Property<int>("TempleLengthMillimeters")
                                .HasColumnType("integer")
                                .HasColumnName("temple_length_mm");

                            b1.HasKey("FrameId");

                            b1.ToTable("frames");

                            b1.WithOwner()
                                .HasForeignKey("FrameId");
                        });

                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
