// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OticaVisao.Infrastructure.Persistence;

#nullable disable

namespace OticaVisao.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908222805_AddBusinessCosts")]
    partial class AddBusinessCosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OticaVisao.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("performed_by");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("OticaVisao.Domain.Catalog.Frame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("color");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("image_file_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("ReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_quantity");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("shape");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("target_audience");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_frames_code");

                    b.ToTable("frames", null, t =>
                        {
                            t.HasCheckConstraint("ck_frames_reserved_quantity", "reserved_quantity >= 0 AND reserved_quantity <= stock_quantity");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Brand = "Linha Visão",
                            Code = "ARM-001",
                            Color = "Preto",
                            IsActive = true,
                            IsPublished = true,
                            Model = "Clássica",
                            Price = 219m,
                            ReservedQuantity = 0,
                            Shape = "Square",
                            StockQuantity = 1,
                            TargetAudience = "Adult",
                            Type = "Prescription"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Brand = "Linha Visão",
                            Code = "ARM-002",
                            Color = "Tartaruga",
                            IsActive = true,
                            IsPublished = true,
                            Model = "Leve",
                            Price = 219m,
                            ReservedQuantity = 0,
                            Shape = "Round",
                            StockQuantity = 1,
                            TargetAudience = "Adult",
                            Type = "Prescription"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Brand = "Linha Visão",
                            Code = "ARM-003",
                            Color = "Preto",
                            IsActive = true,
                            IsPublished = true,
                            Model = "Solar",
                            Price = 219m,
                            ReservedQuantity = 0,
                            Shape = "Aviator",
                            StockQuantity = 1,
                            TargetAudience = "Adult",
                            Type = "Sunglasses"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Brand = "Linha Visão",
                            Code = "ARM-004",
                            Color = "Azul",
                            IsActive = true,
                            IsPublished = true,
                            Model = "Colorida",
                            Price = 219m,
                            ReservedQuantity = 0,
                            Shape = "Round",
                            StockQuantity = 1,
                            TargetAudience = "Child",
                            Type = "Prescription"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Brand = "Linha Visão",
                            Code = "ARM-005",
                            Color = "Dourado",
                            IsActive = true,
                            IsPublished = true,
                            Model = "Minimal",
                            Price = 219m,
                            ReservedQuantity = 0,
                            Shape = "Other",
                            StockQuantity = 1,
                            TargetAudience = "Adult",
                            Type = "Prescription"
                        });
                });

            modelBuilder.Entity("OticaVisao.Domain.Costs.BusinessCost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("IncurredOn")
                        .HasColumnType("date")
                        .HasColumnName("incurred_on");

                    b.HasKey("Id");

                    b.HasIndex("IncurredOn")
                        .HasDatabaseName("ix_business_costs_incurred_on");

                    b.ToTable("business_costs", (string)null);
                });

            modelBuilder.Entity("OticaVisao.Domain.Costs.MonthlyCostBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.HasKey("Id");

                    b.HasIndex("Month")
                        .IsUnique()
                        .HasDatabaseName("ix_monthly_cost_budgets_month");

                    b.ToTable("monthly_cost_budgets", (string)null);
                });

            modelBuilder.Entity("OticaVisao.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_user_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AccountUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_account_user_id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_cpf");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_customers_name");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_customers_phone");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("OticaVisao.Domain.Engagement.FrameFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("FrameId")
                        .HasColumnType("uuid")
                        .HasColumnName("frame_id");

                    b.HasKey("Id");

                    b.HasIndex("FrameId");

                    b.HasIndex("CustomerId", "FrameId")
                        .IsUnique();

                    b.ToTable("frame_favorites", (string)null);
                });

            modelBuilder.Entity("OticaVisao.Domain.Engagement.FrameReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FrameId")
                        .HasColumnType("uuid")
                        .HasColumnName("frame_id");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("VisitPeriod")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("visit_period");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.HasIndex("CustomerId", "FrameId")
                        .IsUnique()
                        .HasDatabaseName("ux_frame_reservations_active_customer_frame")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("CustomerId", "Status");

                    b.HasIndex("FrameId", "Status");

                    b.ToTable("frame_reservations", (string)null);
                });

            modelBuilder.Entity("OticaVisao.Domain.LaboratoryOrders.LaboratoryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at_utc");

                    b.Property<string>("DocumentFileName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("document_file_name");

                    b.Property<DateOnly?>("ExpectedDeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_delivery_date");

                    b.Property<string>("Laboratory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("laboratory");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("ReadyAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at_utc");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<Guid>("SaleItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_item_id");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.HasIndex("SaleItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_laboratory_orders_sale_item_id");

                    b.HasIndex("Status", "ExpectedDeliveryDate")
                        .HasDatabaseName("ix_laboratory_orders_status_expected_date");

                    b.ToTable("laboratory_orders", (string)null);
                });

            modelBuilder.Entity("OticaVisao.Domain.LaboratoryOrders.LaboratoryOrderHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid>("LaboratoryOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("laboratory_order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LaboratoryOrderId", "ChangedAtUtc")
                        .HasDatabaseName("ix_laboratory_order_history_order_date");

                    b.ToTable("laboratory_order_history", (string)null);
                });

            modelBuilder.Entity("OticaVisao.Domain.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal?>("FinalTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("final_total");

                    b.Property<int?>("Installments")
                        .HasColumnType("integer")
                        .HasColumnName("installments");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("ReversalReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reversal_reason");

                    b.Property<DateTimeOffset?>("ReversedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reversed_at_utc");

                    b.Property<string>("ReversedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reversed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_customer_id");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_sales_status_created_at");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("OticaVisao.Domain.Sales.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ExpectedDeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_delivery_date");

                    b.Property<decimal?>("FarLeftAddition")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("far_left_addition");

                    b.Property<int?>("FarLeftAxis")
                        .HasColumnType("integer")
                        .HasColumnName("far_left_axis");

                    b.Property<decimal?>("FarLeftCylinder")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("far_left_cylinder");

                    b.Property<decimal?>("FarLeftDnp")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("far_left_dnp");

                    b.Property<decimal?>("FarLeftHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("far_left_height");

                    b.Property<decimal?>("FarLeftSphere")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("far_left_sphere");

                    b.Property<decimal?>("FarRightAddition")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("far_right_addition");

                    b.Property<int?>("FarRightAxis")
                        .HasColumnType("integer")
                        .HasColumnName("far_right_axis");

                    b.Property<decimal?>("FarRightCylinder")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("far_right_cylinder");

                    b.Property<decimal?>("FarRightDnp")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("far_right_dnp");

                    b.Property<decimal?>("FarRightHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("far_right_height");

                    b.Property<decimal?>("FarRightSphere")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("far_right_sphere");

                    b.Property<string>("FrameBrand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("frame_brand");

                    b.Property<string>("FrameCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("frame_code");

                    b.Property<string>("FrameColor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("frame_color");

                    b.Property<Guid>("FrameId")
                        .HasColumnType("uuid")
                        .HasColumnName("frame_id");

                    b.Property<string>("FrameModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("frame_model");

                    b.Property<decimal>("FrameUnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("frame_unit_price");

                    b.Property<bool>("IncludesLenses")
                        .HasColumnType("boolean")
                        .HasColumnName("includes_lenses");

                    b.Property<string>("Laboratory")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("laboratory");

                    b.Property<string>("LensDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("lens_description");

                    b.Property<decimal>("LensUnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("lens_unit_price");

                    b.Property<decimal?>("NearLeftAddition")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("near_left_addition");

                    b.Property<int?>("NearLeftAxis")
                        .HasColumnType("integer")
                        .HasColumnName("near_left_axis");

                    b.Property<decimal?>("NearLeftCylinder")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("near_left_cylinder");

                    b.Property<decimal?>("NearLeftDnp")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("near_left_dnp");

                    b.Property<decimal?>("NearLeftHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("near_left_height");

                    b.Property<decimal?>("NearLeftSphere")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("near_left_sphere");

                    b.Property<decimal?>("NearRightAddition")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("near_right_addition");

                    b.Property<int?>("NearRightAxis")
                        .HasColumnType("integer")
                        .HasColumnName("near_right_axis");

                    b.Property<decimal?>("NearRightCylinder")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("near_right_cylinder");

                    b.Property<decimal?>("NearRightDnp")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("near_right_dnp");

                    b.Property<decimal?>("NearRightHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("near_right_height");

                    b.Property<decimal?>("NearRightSphere")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("near_right_sphere");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.HasKey("Id");

                    b.HasIndex("FrameId")
                        .HasDatabaseName("ix_sale_items_frame_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_items_sale_id");

                    b.ToTable("sale_items", (string)null);
                });

            modelBuilder.Entity("OticaVisao.Infrastructure.Authentication.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OticaVisao.Infrastructure.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OticaVisao.Infrastructure.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OticaVisao.Infrastructure.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OticaVisao.Infrastructure.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OticaVisao.Domain.Catalog.Frame", b =>
                {
                    b.OwnsOne("OticaVisao.Domain.Catalog.FrameMeasurements", "Measurements", b1 =>
                        {
                            b1.Property<Guid>("FrameId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BridgeWidthMillimeters")
                                .HasColumnType("integer")
                                .HasColumnName("bridge_width_mm");

                            b1.Property<int>("LensWidthMillimeters")
                                .HasColumnType("integer")
                                .HasColumnName("lens_width_mm");

                            b1.Property<int>("TempleLengthMillimeters")
                                .HasColumnType("integer")
                                .HasColumnName("temple_length_mm");

                            b1.HasKey("FrameId");

                            b1.ToTable("frames");

                            b1.WithOwner()
                                .HasForeignKey("FrameId");
                        });

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("OticaVisao.Domain.Customers.Customer", b =>
                {
                    b.HasOne("OticaVisao.Infrastructure.Authentication.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("OticaVisao.Domain.Customers.Customer", "AccountUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("OticaVisao.Domain.Customers.CustomerAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("address_complement");

                            b1.Property<string>("Neighborhood")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("neighborhood");

                            b1.Property<string>("Number")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(9)
                                .HasColumnType("character varying(9)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("State")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("state");

                            b1.Property<string>("Street")
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("OticaVisao.Domain.Engagement.FrameFavorite", b =>
                {
                    b.HasOne("OticaVisao.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OticaVisao.Domain.Catalog.Frame", null)
                        .WithMany()
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OticaVisao.Domain.Engagement.FrameReservation", b =>
                {
                    b.HasOne("OticaVisao.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OticaVisao.Domain.Catalog.Frame", null)
                        .WithMany()
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OticaVisao.Domain.Sales.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("OticaVisao.Domain.LaboratoryOrders.LaboratoryOrder", b =>
                {
                    b.HasOne("OticaVisao.Domain.Sales.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OticaVisao.Domain.Sales.SaleItem", "SaleItem")
                        .WithMany()
                        .HasForeignKey("SaleItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sale");

                    b.Navigation("SaleItem");
                });

            modelBuilder.Entity("OticaVisao.Domain.LaboratoryOrders.LaboratoryOrderHistory", b =>
                {
                    b.HasOne("OticaVisao.Domain.LaboratoryOrders.LaboratoryOrder", null)
                        .WithMany("History")
                        .HasForeignKey("LaboratoryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OticaVisao.Domain.Sales.Sale", b =>
                {
                    b.HasOne("OticaVisao.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OticaVisao.Domain.Sales.SaleItem", b =>
                {
                    b.HasOne("OticaVisao.Domain.Catalog.Frame", "Frame")
                        .WithMany()
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OticaVisao.Domain.Sales.Sale", null)
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");
                });

            modelBuilder.Entity("OticaVisao.Domain.LaboratoryOrders.LaboratoryOrder", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("OticaVisao.Domain.Sales.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
